"""Schemas for anticipatory alerts and analyst workflow management."""

from datetime import datetime, timezone
from enum import Enum
from typing import Dict, List, Optional
from pydantic import BaseModel, Field
from aegis_wm.schemas.labels import AttackStageEnum


class AlertSeverityEnum(str, Enum):
    INFORMATIONAL = "informational"
    WATCH = "watch"
    WARNING = "warning"
    CRITICAL = "critical"


class AlertStateEnum(str, Enum):
    ACTIVE = "active"
    ACKNOWLEDGED = "acknowledged"
    INVESTIGATING = "investigating"
    RESOLVED = "resolved"
    FALSE_POSITIVE = "false_positive"


class AlertRecord(BaseModel):
    """Detection alert generated by the anticipatory policy engine."""

    alert_id: str
    analysis_id: str
    forecast_id: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    severity: AlertSeverityEnum
    state: AlertStateEnum = AlertStateEnum.ACTIVE

    # Anticipatory Attack Details
    forecast_horizon_seconds: float = Field(..., description="Lead time to predicted compromise (seconds)")
    forecast_horizon_steps: int = Field(..., description="Horizon step k (windows ahead)")
    infiltration_probability: float = Field(..., ge=0.0, le=1.0)
    uncertainty_range: float = Field(..., ge=0.0, le=1.0)
    predicted_stage: AttackStageEnum

    # Evidence Context
    primary_host_pseudo: Optional[str] = None
    top_indicator_features: List[str] = Field(default_factory=list)
    supporting_flow_count: int = 0
    policy_rule_triggered: str = Field(..., description="Policy rule identifier")

    # Analyst Workflow
    acknowledged_by: Optional[str] = None
    acknowledged_at: Optional[datetime] = None
    analyst_notes: Optional[str] = None
